//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: fulbo_presale
// ----------------------------------------------------------------------------
pub mod fulbo_presale {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for fulbo_presale
    pub fn program_id() -> Pubkey {
        pubkey!("4q6B6GdbbijEHxnhXVx8mDsiHfgk5b9bCVB8PqtA1bDJ")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AnnounceTge
    // ....................................................................

    /// Main instruction struct for AnnounceTge
    pub struct AnnounceTgeInstruction {
        pub accounts: AnnounceTgeInstructionAccountMetas,
        pub data: AnnounceTgeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AnnounceTge instruction
    #[derive(Debug, Clone, Default)]
    pub struct AnnounceTgeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for AnnounceTge instruction
    #[derive(Debug, Clone)]
    pub struct AnnounceTgeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl AnnounceTgeInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for AnnounceTge
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AnnounceTgeInstructionData {}

    impl AnnounceTgeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AnnounceTgeInstruction
    impl AnnounceTgeInstruction {
        fn discriminator() -> [u8; 8] {
            [24u8, 154u8, 46u8, 27u8, 224u8, 183u8, 10u8, 4u8]
        }

        pub fn data(data: AnnounceTgeInstructionData) -> Self {
            Self {
                accounts: AnnounceTgeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AnnounceTgeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BeneficiaryClaim
    // ....................................................................

    /// Main instruction struct for BeneficiaryClaim
    pub struct BeneficiaryClaimInstruction {
        pub accounts: BeneficiaryClaimInstructionAccountMetas,
        pub data: BeneficiaryClaimInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BeneficiaryClaim instruction
    #[derive(Debug, Clone, Default)]
    pub struct BeneficiaryClaimInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary_allocation: AccountMeta,

        pub mint: AccountMeta,

        pub treasury_ata: AccountMeta,

        pub beneficiary_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for BeneficiaryClaim instruction
    #[derive(Debug, Clone)]
    pub struct BeneficiaryClaimInstructionAccounts {
        pub beneficiary: Pubkey,

        pub config: Pubkey,

        pub beneficiary_allocation: Pubkey,

        pub mint: Pubkey,

        pub treasury_ata: Pubkey,

        pub beneficiary_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl BeneficiaryClaimInstructionAccounts {
        pub fn new(
            beneficiary: Pubkey,

            config: Pubkey,

            beneficiary_allocation: Pubkey,

            mint: Pubkey,

            treasury_ata: Pubkey,

            beneficiary_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                beneficiary,

                config,

                beneficiary_allocation,

                mint,

                treasury_ata,

                beneficiary_ata,

                token_program,
            }
        }
    }

    /// Instruction data for BeneficiaryClaim
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BeneficiaryClaimInstructionData {}

    impl BeneficiaryClaimInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for BeneficiaryClaimInstruction
    impl BeneficiaryClaimInstruction {
        fn discriminator() -> [u8; 8] {
            [190u8, 120u8, 36u8, 208u8, 178u8, 6u8, 10u8, 76u8]
        }

        pub fn data(data: BeneficiaryClaimInstructionData) -> Self {
            Self {
                accounts: BeneficiaryClaimInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BeneficiaryClaimInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.beneficiary_allocation =
                AccountMeta::new(accounts.beneficiary_allocation, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.treasury_ata = AccountMeta::new(accounts.treasury_ata, false);

            self.accounts.beneficiary_ata = AccountMeta::new(accounts.beneficiary_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary_allocation.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.treasury_ata.clone());

            metas.push(self.accounts.beneficiary_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BuyToken
    // ....................................................................

    /// Main instruction struct for BuyToken
    pub struct BuyTokenInstruction {
        pub accounts: BuyTokenInstructionAccountMetas,
        pub data: BuyTokenInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BuyToken instruction
    #[derive(Debug, Clone, Default)]
    pub struct BuyTokenInstructionAccountMetas {
        pub buyer: AccountMeta,

        pub config: AccountMeta,

        pub treasury: AccountMeta,

        pub position: AccountMeta,

        pub chainlink_feed: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for BuyToken instruction
    #[derive(Debug, Clone)]
    pub struct BuyTokenInstructionAccounts {
        pub buyer: Pubkey,

        pub config: Pubkey,

        pub treasury: Pubkey,

        pub position: Pubkey,

        pub chainlink_feed: Pubkey,
    }

    impl BuyTokenInstructionAccounts {
        pub fn new(
            buyer: Pubkey,

            config: Pubkey,

            treasury: Pubkey,

            position: Pubkey,

            chainlink_feed: Pubkey,
        ) -> Self {
            Self {
                buyer,

                config,

                treasury,

                position,

                chainlink_feed,
            }
        }
    }

    /// Instruction data for BuyToken
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BuyTokenInstructionData {
        pub amount: u64,
    }

    impl BuyTokenInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BuyTokenInstruction
    impl BuyTokenInstruction {
        fn discriminator() -> [u8; 8] {
            [138u8, 127u8, 14u8, 91u8, 38u8, 87u8, 115u8, 105u8]
        }

        pub fn data(data: BuyTokenInstructionData) -> Self {
            Self {
                accounts: BuyTokenInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BuyTokenInstructionAccounts) -> Self {
            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.chainlink_feed =
                AccountMeta::new_readonly(accounts.chainlink_feed, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.chainlink_feed.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimToken
    // ....................................................................

    /// Main instruction struct for ClaimToken
    pub struct ClaimTokenInstruction {
        pub accounts: ClaimTokenInstructionAccountMetas,
        pub data: ClaimTokenInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimToken instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimTokenInstructionAccountMetas {
        pub claimer: AccountMeta,

        pub config: AccountMeta,

        pub position: AccountMeta,

        pub mint: AccountMeta,

        pub treasury_ata: AccountMeta,

        pub claimer_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for ClaimToken instruction
    #[derive(Debug, Clone)]
    pub struct ClaimTokenInstructionAccounts {
        pub claimer: Pubkey,

        pub config: Pubkey,

        pub position: Pubkey,

        pub mint: Pubkey,

        pub treasury_ata: Pubkey,

        pub claimer_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl ClaimTokenInstructionAccounts {
        pub fn new(
            claimer: Pubkey,

            config: Pubkey,

            position: Pubkey,

            mint: Pubkey,

            treasury_ata: Pubkey,

            claimer_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                claimer,

                config,

                position,

                mint,

                treasury_ata,

                claimer_ata,

                token_program,
            }
        }
    }

    /// Instruction data for ClaimToken
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimTokenInstructionData {}

    impl ClaimTokenInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimTokenInstruction
    impl ClaimTokenInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 206u8, 27u8, 191u8, 166u8, 19u8, 0u8, 73u8]
        }

        pub fn data(data: ClaimTokenInstructionData) -> Self {
            Self {
                accounts: ClaimTokenInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimTokenInstructionAccounts) -> Self {
            self.accounts.claimer = AccountMeta::new(accounts.claimer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.treasury_ata = AccountMeta::new(accounts.treasury_ata, false);

            self.accounts.claimer_ata = AccountMeta::new(accounts.claimer_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.claimer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.treasury_ata.clone());

            metas.push(self.accounts.claimer_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FinalizeUnsold
    // ....................................................................

    /// Main instruction struct for FinalizeUnsold
    pub struct FinalizeUnsoldInstruction {
        pub accounts: FinalizeUnsoldInstructionAccountMetas,
        pub data: FinalizeUnsoldInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FinalizeUnsold instruction
    #[derive(Debug, Clone, Default)]
    pub struct FinalizeUnsoldInstructionAccountMetas {
        pub authority: AccountMeta,

        pub rewards_beneficiary: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary_allocation: AccountMeta,

        pub mint: AccountMeta,

        pub treasury_ata: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FinalizeUnsold instruction
    #[derive(Debug, Clone)]
    pub struct FinalizeUnsoldInstructionAccounts {
        pub authority: Pubkey,

        pub rewards_beneficiary: Pubkey,

        pub config: Pubkey,

        pub beneficiary_allocation: Pubkey,

        pub mint: Pubkey,

        pub treasury_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl FinalizeUnsoldInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            rewards_beneficiary: Pubkey,

            config: Pubkey,

            beneficiary_allocation: Pubkey,

            mint: Pubkey,

            treasury_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                rewards_beneficiary,

                config,

                beneficiary_allocation,

                mint,

                treasury_ata,

                token_program,
            }
        }
    }

    /// Instruction data for FinalizeUnsold
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FinalizeUnsoldInstructionData {}

    impl FinalizeUnsoldInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FinalizeUnsoldInstruction
    impl FinalizeUnsoldInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 134u8, 37u8, 105u8, 63u8, 206u8, 63u8, 94u8]
        }

        pub fn data(data: FinalizeUnsoldInstructionData) -> Self {
            Self {
                accounts: FinalizeUnsoldInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FinalizeUnsoldInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.rewards_beneficiary =
                AccountMeta::new_readonly(accounts.rewards_beneficiary, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.beneficiary_allocation =
                AccountMeta::new(accounts.beneficiary_allocation, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.treasury_ata = AccountMeta::new(accounts.treasury_ata, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.rewards_beneficiary.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary_allocation.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.treasury_ata.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub treasury: AccountMeta,

        pub mint: AccountMeta,

        pub treasury_ata: AccountMeta,

        pub chainlink_feed: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub treasury: Pubkey,

        pub mint: Pubkey,

        pub treasury_ata: Pubkey,

        pub chainlink_feed: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            treasury: Pubkey,

            mint: Pubkey,

            treasury_ata: Pubkey,

            chainlink_feed: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                treasury,

                mint,

                treasury_ata,

                chainlink_feed,

                token_program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub total_tokens_for_sale: u64,

        pub stages: [Stage; 11],
    }

    impl InitializeInstructionData {
        pub fn new(total_tokens_for_sale: u64, stages: [Stage; 11]) -> Self {
            Self {
                total_tokens_for_sale,

                stages,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.treasury_ata = AccountMeta::new(accounts.treasury_ata, false);

            self.accounts.chainlink_feed =
                AccountMeta::new_readonly(accounts.chainlink_feed, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.treasury_ata.clone());

            metas.push(self.accounts.chainlink_feed.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeBeneficiary
    // ....................................................................

    /// Main instruction struct for InitializeBeneficiary
    pub struct InitializeBeneficiaryInstruction {
        pub accounts: InitializeBeneficiaryInstructionAccountMetas,
        pub data: InitializeBeneficiaryInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeBeneficiary instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeBeneficiaryInstructionAccountMetas {
        pub authority: AccountMeta,

        pub beneficiary: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary_allocation: AccountMeta,

        pub treasury_share: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeBeneficiary instruction
    #[derive(Debug, Clone)]
    pub struct InitializeBeneficiaryInstructionAccounts {
        pub authority: Pubkey,

        pub beneficiary: Pubkey,

        pub config: Pubkey,

        pub beneficiary_allocation: Pubkey,

        pub treasury_share: Pubkey,
    }

    impl InitializeBeneficiaryInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            beneficiary: Pubkey,

            config: Pubkey,

            beneficiary_allocation: Pubkey,

            treasury_share: Pubkey,
        ) -> Self {
            Self {
                authority,

                beneficiary,

                config,

                beneficiary_allocation,

                treasury_share,
            }
        }
    }

    /// Instruction data for InitializeBeneficiary
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeBeneficiaryInstructionData {
        pub total_tokens: u64,

        pub tge_unlock_bps: u16,

        pub instant_unlock: bool,

        pub withdraw_interval: i64,

        pub sol_share_bps: u16,
    }

    impl InitializeBeneficiaryInstructionData {
        pub fn new(
            total_tokens: u64,

            tge_unlock_bps: u16,

            instant_unlock: bool,

            withdraw_interval: i64,

            sol_share_bps: u16,
        ) -> Self {
            Self {
                total_tokens,

                tge_unlock_bps,

                instant_unlock,

                withdraw_interval,

                sol_share_bps,
            }
        }
    }

    /// Implementation for InitializeBeneficiaryInstruction
    impl InitializeBeneficiaryInstruction {
        fn discriminator() -> [u8; 8] {
            [191u8, 37u8, 201u8, 204u8, 154u8, 90u8, 127u8, 164u8]
        }

        pub fn data(data: InitializeBeneficiaryInstructionData) -> Self {
            Self {
                accounts: InitializeBeneficiaryInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeBeneficiaryInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.beneficiary = AccountMeta::new_readonly(accounts.beneficiary, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.beneficiary_allocation =
                AccountMeta::new(accounts.beneficiary_allocation, false);

            self.accounts.treasury_share = AccountMeta::new(accounts.treasury_share, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary_allocation.clone());

            metas.push(self.accounts.treasury_share.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeRewardsBeneficiary
    // ....................................................................

    /// Main instruction struct for InitializeRewardsBeneficiary
    pub struct InitializeRewardsBeneficiaryInstruction {
        pub accounts: InitializeRewardsBeneficiaryInstructionAccountMetas,
        pub data: InitializeRewardsBeneficiaryInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeRewardsBeneficiary instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeRewardsBeneficiaryInstructionAccountMetas {
        pub authority: AccountMeta,

        pub beneficiary: AccountMeta,

        pub config: AccountMeta,

        pub beneficiary_allocation: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeRewardsBeneficiary instruction
    #[derive(Debug, Clone)]
    pub struct InitializeRewardsBeneficiaryInstructionAccounts {
        pub authority: Pubkey,

        pub beneficiary: Pubkey,

        pub config: Pubkey,

        pub beneficiary_allocation: Pubkey,
    }

    impl InitializeRewardsBeneficiaryInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            beneficiary: Pubkey,

            config: Pubkey,

            beneficiary_allocation: Pubkey,
        ) -> Self {
            Self {
                authority,

                beneficiary,

                config,

                beneficiary_allocation,
            }
        }
    }

    /// Instruction data for InitializeRewardsBeneficiary
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeRewardsBeneficiaryInstructionData {
        pub total_tokens: u64,
    }

    impl InitializeRewardsBeneficiaryInstructionData {
        pub fn new(total_tokens: u64) -> Self {
            Self { total_tokens }
        }
    }

    /// Implementation for InitializeRewardsBeneficiaryInstruction
    impl InitializeRewardsBeneficiaryInstruction {
        fn discriminator() -> [u8; 8] {
            [94u8, 146u8, 172u8, 142u8, 210u8, 8u8, 161u8, 242u8]
        }

        pub fn data(data: InitializeRewardsBeneficiaryInstructionData) -> Self {
            Self {
                accounts: InitializeRewardsBeneficiaryInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeRewardsBeneficiaryInstructionAccounts,
        ) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.beneficiary = AccountMeta::new_readonly(accounts.beneficiary, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.beneficiary_allocation =
                AccountMeta::new(accounts.beneficiary_allocation, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.beneficiary_allocation.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawTreasury
    // ....................................................................

    /// Main instruction struct for WithdrawTreasury
    pub struct WithdrawTreasuryInstruction {
        pub accounts: WithdrawTreasuryInstructionAccountMetas,
        pub data: WithdrawTreasuryInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawTreasury instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawTreasuryInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub beneficiary_treasury: AccountMeta,

        pub treasury: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawTreasury instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawTreasuryInstructionAccounts {
        pub beneficiary: Pubkey,

        pub beneficiary_treasury: Pubkey,

        pub treasury: Pubkey,

        pub config: Pubkey,
    }

    impl WithdrawTreasuryInstructionAccounts {
        pub fn new(
            beneficiary: Pubkey,

            beneficiary_treasury: Pubkey,

            treasury: Pubkey,

            config: Pubkey,
        ) -> Self {
            Self {
                beneficiary,

                beneficiary_treasury,

                treasury,

                config,
            }
        }
    }

    /// Instruction data for WithdrawTreasury
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawTreasuryInstructionData {}

    impl WithdrawTreasuryInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawTreasuryInstruction
    impl WithdrawTreasuryInstruction {
        fn discriminator() -> [u8; 8] {
            [40u8, 63u8, 122u8, 158u8, 144u8, 216u8, 83u8, 96u8]
        }

        pub fn data(data: WithdrawTreasuryInstructionData) -> Self {
            Self {
                accounts: WithdrawTreasuryInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawTreasuryInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.beneficiary_treasury =
                AccountMeta::new(accounts.beneficiary_treasury, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.beneficiary_treasury.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: BeneficiaryAllocation
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BeneficiaryAllocation {
    pub total_tokens: u64,

    pub withdrawn_tokens: u64,

    pub monthly_unlocked: u64,

    pub tge_unlock_bps: u16,

    pub instant_unlock: bool,

    pub bump: u8,
}

impl BeneficiaryAllocation {
    pub fn new(
        total_tokens: u64,

        withdrawn_tokens: u64,

        monthly_unlocked: u64,

        tge_unlock_bps: u16,

        instant_unlock: bool,

        bump: u8,
    ) -> Self {
        Self {
            total_tokens,

            withdrawn_tokens,

            monthly_unlocked,

            tge_unlock_bps,

            instant_unlock,

            bump,
        }
    }
}

/// Custom struct: BeneficiaryInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BeneficiaryInitialized {
    pub beneficiary: Pubkey,

    pub total_tokens: u64,

    pub tge_unlock_bps: u16,

    pub sol_share_bps: u16,
}

impl BeneficiaryInitialized {
    pub fn new(
        beneficiary: Pubkey,

        total_tokens: u64,

        tge_unlock_bps: u16,

        sol_share_bps: u16,
    ) -> Self {
        Self {
            beneficiary,

            total_tokens,

            tge_unlock_bps,

            sol_share_bps,
        }
    }
}

/// Custom struct: BeneficiaryTokensClaimed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BeneficiaryTokensClaimed {
    pub beneficiary: Pubkey,

    pub amount: u64,
}

impl BeneficiaryTokensClaimed {
    pub fn new(beneficiary: Pubkey, amount: u64) -> Self {
        Self {
            beneficiary,

            amount,
        }
    }
}

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub chainlink_feed: Pubkey,

    pub stages: [Stage; 11],

    pub tge_timestamp: i64,

    pub presale_start_timestamp: i64,

    pub total_sol_raised: u64,

    pub total_tokens_for_sale: u64,

    pub total_tokens_sold: u64,

    pub total_tokens_claimed: u64,

    pub unsold_finalized: bool,

    pub total_sol_shares_bps: u16,

    pub current_stage: u8,

    pub sale_finalized: bool,

    pub paused: bool,

    pub treasury_ata_bump: u8,

    pub bump: u8,
}

impl Config {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        chainlink_feed: Pubkey,

        stages: [Stage; 11],

        tge_timestamp: i64,

        presale_start_timestamp: i64,

        total_sol_raised: u64,

        total_tokens_for_sale: u64,

        total_tokens_sold: u64,

        total_tokens_claimed: u64,

        unsold_finalized: bool,

        total_sol_shares_bps: u16,

        current_stage: u8,

        sale_finalized: bool,

        paused: bool,

        treasury_ata_bump: u8,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            mint,

            chainlink_feed,

            stages,

            tge_timestamp,

            presale_start_timestamp,

            total_sol_raised,

            total_tokens_for_sale,

            total_tokens_sold,

            total_tokens_claimed,

            unsold_finalized,

            total_sol_shares_bps,

            current_stage,

            sale_finalized,

            paused,

            treasury_ata_bump,

            bump,
        }
    }
}

/// Custom struct: Position
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Position {
    pub total_tokens: u64,

    pub total_sol: u64,

    pub tokens_claimed: u64,

    pub stage_allocations: [StageAllocation; 11],

    pub is_initialized: bool,

    pub bump: u8,
}

impl Position {
    pub fn new(
        total_tokens: u64,

        total_sol: u64,

        tokens_claimed: u64,

        stage_allocations: [StageAllocation; 11],

        is_initialized: bool,

        bump: u8,
    ) -> Self {
        Self {
            total_tokens,

            total_sol,

            tokens_claimed,

            stage_allocations,

            is_initialized,

            bump,
        }
    }
}

/// Custom struct: SaleFinalized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SaleFinalized {
    pub tge_timestamp: i64,

    pub total_tokens_sold: u64,

    pub total_sol_raised: u64,
}

impl SaleFinalized {
    pub fn new(tge_timestamp: i64, total_tokens_sold: u64, total_sol_raised: u64) -> Self {
        Self {
            tge_timestamp,

            total_tokens_sold,

            total_sol_raised,
        }
    }
}

/// Custom struct: SalePaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SalePaused {}

impl SalePaused {
    pub fn new() -> Self {
        Self {}
    }
}

/// Custom struct: SaleUnpaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SaleUnpaused {}

impl SaleUnpaused {
    pub fn new() -> Self {
        Self {}
    }
}

/// Custom struct: Stage
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Stage {
    pub price_usd: u64,

    pub max_tokens: u64,

    pub tokens_sold: u64,

    pub raised_sol: u64,

    pub locked_pct_bps: u16,

    pub max_wallet_pct_bps: u16,
}

impl Stage {
    pub fn new(
        price_usd: u64,

        max_tokens: u64,

        tokens_sold: u64,

        raised_sol: u64,

        locked_pct_bps: u16,

        max_wallet_pct_bps: u16,
    ) -> Self {
        Self {
            price_usd,

            max_tokens,

            tokens_sold,

            raised_sol,

            locked_pct_bps,

            max_wallet_pct_bps,
        }
    }
}

/// Custom struct: StageAllocation
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StageAllocation {
    pub tokens: u64,

    pub sol_paid: u64,

    pub claimed: u64,

    pub locked_pct_bps: u16,
}

impl StageAllocation {
    pub fn new(tokens: u64, sol_paid: u64, claimed: u64, locked_pct_bps: u16) -> Self {
        Self {
            tokens,

            sol_paid,

            claimed,

            locked_pct_bps,
        }
    }
}

/// Custom struct: TgeAnnounced
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TgeAnnounced {
    pub tge_timestamp: i64,
}

impl TgeAnnounced {
    pub fn new(tge_timestamp: i64) -> Self {
        Self { tge_timestamp }
    }
}

/// Custom struct: TokenPurchased
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokenPurchased {
    pub buyer: Pubkey,

    pub stage: u8,

    pub tokens: u64,

    pub lamports: u64,
}

impl TokenPurchased {
    pub fn new(buyer: Pubkey, stage: u8, tokens: u64, lamports: u64) -> Self {
        Self {
            buyer,

            stage,

            tokens,

            lamports,
        }
    }
}

/// Custom struct: TokensClaimed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensClaimed {
    pub claimer: Pubkey,

    pub total_claimable: u64,
}

impl TokensClaimed {
    pub fn new(claimer: Pubkey, total_claimable: u64) -> Self {
        Self {
            claimer,

            total_claimable,
        }
    }
}

/// Custom struct: Treasury
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Treasury {
    pub total_sol: u64,

    pub withdrawn_sol: u64,

    pub bump: u8,
}

impl Treasury {
    pub fn new(total_sol: u64, withdrawn_sol: u64, bump: u8) -> Self {
        Self {
            total_sol,

            withdrawn_sol,

            bump,
        }
    }
}

/// Custom struct: TreasuryShare
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TreasuryShare {
    pub sol_withdrawn: u64,

    pub last_sol_claim: i64,

    pub presale_start: i64,

    pub withdraw_interval: i64,

    pub sol_share_bps: u16,

    pub instant_unlock: bool,

    pub bump: u8,
}

impl TreasuryShare {
    pub fn new(
        sol_withdrawn: u64,

        last_sol_claim: i64,

        presale_start: i64,

        withdraw_interval: i64,

        sol_share_bps: u16,

        instant_unlock: bool,

        bump: u8,
    ) -> Self {
        Self {
            sol_withdrawn,

            last_sol_claim,

            presale_start,

            withdraw_interval,

            sol_share_bps,

            instant_unlock,

            bump,
        }
    }
}

/// Custom struct: TreasuryWithdrawn
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TreasuryWithdrawn {
    pub beneficiary: Pubkey,

    pub amount: u64,
}

impl TreasuryWithdrawn {
    pub fn new(beneficiary: Pubkey, amount: u64) -> Self {
        Self {
            beneficiary,

            amount,
        }
    }
}

/// Custom struct: UnsoldTokensFinalized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UnsoldTokensFinalized {
    pub burned: u64,

    pub rewarded: u64,
}

impl UnsoldTokensFinalized {
    pub fn new(burned: u64, rewarded: u64) -> Self {
        Self { burned, rewarded }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
